
package com.example.persistence;

import com.example.loginform.BuildConfig;
import com.example.objects.Book;
import com.example.objects.User;
import java.sql.*;
import java.util.ArrayList;
import java.util.Locale;

public class UsersDB
{
    private String dbPath;
    private static String TAG = "UsersDB";
    private Connection conn;
    private static String DBName = "appdatabase.db";

    private static final String TABLE2 = "users";
    private static final String UID = "id";
    private static final String UFNAME = "firstname";
    private static final String ULNAME = "lastname";
    private static final String UEMAIL = "email";
    private static final String UPASSWORD = "password";

    public UsersDB(String dbPath)
    {
        this.dbPath = dbPath;
    }

    private boolean ConnectToUsersDB()
    {
        try
        {
            DriverManager.registerDriver((Driver) Class.forName("org.hsqldb.jdbcDriver").newInstance());
            conn = DriverManager.getConnection("jdbc:hsqldb:file:"  + dbPath + ";hsqldb.lock_file=false;shutdown=true", "SA", "");
        }
        catch (Exception e)
        {
            //Log.e(TAG, "Unable to connect. Error: " + e.getMessage());
            return false;
        }

        return true;
    }

    public boolean CreateSchema()
    {
        String dbSchema = "CREATE SCHEMA IF NOT EXISTS appschema";
        return ExecuteQuery(dbSchema);
    }

    public boolean ResetDB() {
        if (ConnectToUsersDB()) {
            try {
                Statement stmt = conn.createStatement();
                stmt.executeUpdate("TRUNCATE TABLE " + TABLE2 + " RESTART IDENTITY");
                stmt.close();
                //conn.close();
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        } else {
            return false;
        }

        return true;
    }

    // Creates a table if it does not exist
    public boolean CreateDB()
    {
        if (!CreateSchema())
            return false;

        String createUsers = "CREATE TABLE IF NOT EXISTS " + TABLE2 + " (" + UID + " INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + UFNAME + " VARCHAR(50), " + ULNAME + " VARCHAR(50), " + UEMAIL + " VARCHAR(50), " + UPASSWORD + " VARCHAR(50))";

        if (ConnectToUsersDB()) {
            return ExecuteQuery(createUsers);
        }
        return false;
    }

    public boolean ExecuteQuery(String query)
    {
        if (ConnectToUsersDB())
        {
            try
            {
                Statement stmt = conn.createStatement();
                stmt.executeUpdate(query);
                stmt.close();
                //conn.close();
            }
            catch (Exception e)
            {
                //Log.e(TAG, "Unable to execute query: " + query + ". Error: " + e.getMessage());
                return false;
            }

            return true;
        }

        return false;
    }

    public boolean InsertUser(String firstName, String lastName, String email, String password)
    {
        String newBook = "INSERT INTO " + TABLE2 + " (" + UFNAME + ", " + ULNAME + ", " + UEMAIL + ", " + UPASSWORD + ") VALUES (?, ?, ?, ?)";
        if (ConnectToUsersDB()) {
            try {
                PreparedStatement stmt = conn.prepareStatement(newBook);
                stmt.setString(1, firstName);
                stmt.setString(2, lastName);
                stmt.setString(3, email);
                stmt.setString(4, password);
                stmt.executeUpdate();
                stmt.close();
                //conn.close();
            }
            catch (Exception e)
            {
                //Log.e(TAG, "Unable to insert data. Error: " + e.getMessage());
                return false;
            }
            return true;
        }
        return false;
    }

    public ArrayList<User> GetUsers() {
        ArrayList<User> users = new ArrayList<User>();
        String getUsers = "SELECT * FROM users;";

        if (ConnectToUsersDB()) {
            try {
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(getUsers);

                while (rs.next()) {
                    User user = new User(rs.getInt(UID),
                            rs.getString(UFNAME),
                            rs.getString(ULNAME),
                            rs.getString(UEMAIL),
                            rs.getString(UPASSWORD));
                    //Log.i(TAG, user.getFirstName());
                    users.add(user);
                }

                stmt.close();

            } catch (Exception e) {
                //Log.e(TAG, "Unable to get users. Error: " + e.getMessage());
                System.out.println("Error UsersDB: " + e.getMessage());
                return null;
            }
        }

        return users;
    }
}