package com.uom.thebookstore.persistence;

import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

public class CartsDB
{
    private String dbPath;
    private String DBName = "appdb.db";
    private static String TAG = "CartsDB";
    private Connection conn;

    // Table Schema
    private static final String TABLE3 = "carts";
    private static final String CID = "id";
    private static final String BID = "book_id";
    private static final String UID = "user_id";
    private static final String CSTATUS = "status";

    public CartsDB(String dbPath)
    {
        this.dbPath = dbPath;
    }

    private boolean ConnectToCartsDB()
    {
        try
        {
            DriverManager.registerDriver((Driver) Class.forName("org.hsqldb.jdbcDriver").newInstance());
            conn = DriverManager.getConnection("jdbc:hsqldb:file:"  + dbPath + ";hsqldb.lock_file=false;shutdown=true", "SA", "");
        }
        catch (Exception e)
        {
            //Log.e(TAG, "Unable to connect. Error: " + e.getMessage());
            return false;
        }

        return true;
    }

    public boolean CreateSchema()
    {
        String dbSchema = "CREATE SCHEMA IF NOT EXISTS appschema";
        return ExecuteQuery(dbSchema);
    }

    public boolean CreateDB()
    {
        if (!CreateSchema())
            return false;

        String createUsers = "CREATE TABLE IF NOT EXISTS " + TABLE3 + " (" + CID + " INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + UID + " INTEGER, " + BID + " INTEGER, " + CSTATUS + " BOOLEAN)";

        if (ConnectToCartsDB()) {
            return ExecuteQuery(createUsers);
        }

        return false;
    }

    public boolean ExecuteQuery(String query)
    {
        if (ConnectToCartsDB())
        {
            try
            {
                Statement stmt = conn.createStatement();
                stmt.executeUpdate(query);
                stmt.close();
                //conn.close();
            }
            catch (Exception e)
            {
                //Log.e(TAG, "Unable to execute query: " + query + ". Error: " + e.getMessage());
                return false;
            }

            return true;
        }

        return false;
    }

    public boolean ChangeStatus(int bID, int uID, boolean status)
    {
        String updateStatus = "UPDATE " + TABLE3 + " SET " + CSTATUS + " = ? WHERE UID = ? AND BID = ?";
        if (ConnectToCartsDB()) {
            try {
                PreparedStatement stmt = conn.prepareStatement(updateStatus);
                stmt.setBoolean(1, status); // false to remove it from the cart
                stmt.setInt(2, uID);
                stmt.setInt(3, bID);
                stmt.executeUpdate();
                stmt.close();
                //conn.close();
            }
            catch (Exception e)
            {
                //Log.e(TAG, "Unable to insert data. Error: " + e.getMessage());
                return false;
            }
            return true;
        }
        return false;
    }

    public boolean InsertToCart(int bID, int uID)
    {
        String newCartItem = "INSERT INTO " + TABLE3 + " (" + UID + ", " + BID + ", " + CSTATUS + ") VALUES (?, ?, ?)";

        if (ConnectToCartsDB()) {
            try {
                PreparedStatement stmt = conn.prepareStatement(newCartItem);
                stmt.setInt(1, uID);
                stmt.setInt(2, bID);
                stmt.setBoolean(3, true);
                stmt.executeUpdate();
                stmt.close();
                //conn.close();
            }
            catch (Exception e)
            {
                //Log.e(TAG, "Unable to insert data. Error: " + e.getMessage());
                return false;
            }
            return true;
        }
        return false;
    }

    public boolean ResetDB() {
        if (ConnectToCartsDB()) {
            try {
                Statement stmt = conn.createStatement();
                stmt.executeUpdate("TRUNCATE TABLE " + TABLE3 + " RESTART IDENTITY");
                stmt.close();
                //conn.close();
            } catch (Exception e) {
                System.out.println("DB Reset error: " + e.getMessage());
            }
        } else {
            return false;
        }

        return true;
    }

    public ArrayList<Integer> GetCartFromUser(int uID)
    {
        ArrayList<Integer> bookIDs = new ArrayList<Integer>();
        String getBooks = "SELECT * FROM carts;";

        if (ConnectToCartsDB())
        {
            try
            {
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(getBooks);

                while (rs.next())
                {
                    if(rs.getInt(UID) == uID && rs.getBoolean(CSTATUS) == true)
                    {
                        bookIDs.add(rs.getInt(BID));
                    }
                }

                stmt.close();

            } catch (Exception e) {
                //Log.e(TAG, "Unable to get users. Error: " + e.getMessage());
                return null;
            }
        }

        return bookIDs;
    }

    public ArrayList<Integer> GetOrdersFromUser(int uID)
    {
        ArrayList<Integer> bookIDs = new ArrayList<Integer>();
        String getBooks = "SELECT * FROM carts;";

        if (ConnectToCartsDB())
        {
            try
            {
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(getBooks);

                while (rs.next())
                {
                    if(rs.getInt(UID) == uID && rs.getBoolean(CSTATUS) == false)
                    {
                        bookIDs.add(rs.getInt(BID));
                    }
                }

                stmt.close();

            } catch (Exception e) {
                //Log.e(TAG, "Unable to get users. Error: " + e.getMessage());
                return null;
            }
        }

        return bookIDs;
    }

}
